version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - FASTAPI_PORT=8080
      - REDIS_PORT=6379
      - DB=postgresql
      - DB_USER=postgres
      - DB_PASSWORD=postgres_pass
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      - redis
      - db

  frontend:
    build:
      context: ./dash_frontend
      dockerfile: Dockerfile
    ports:
      - 8050:8050
    depends_on:
      - backend

  worker:
    build:
      context: ./backend
      dockerfile: Dockerfile_worker
    command: python -m models_billing.inference_queue.worker
    environment:
      - FASTAPI_PORT=8080
      - REDIS_PORT=6379
      - DB=postgresql
      - DB_USER=postgres
      - DB_PASSWORD=postgres_pass
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      - backend
      - redis
      - db

  redis:
    image: redis:7-alpine

  db:
    image: postgres:12.17-alpine3.19
    # ports:
    #  - 5432:5432
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres_pass