version: '3.8'

services:
  web:
    build:
      context: ./backend
      dockerfile: Dockerfile
    #command: python manage.py runserver 0.0.0.0:8080
    # volumes:
    #   - ./triton-facade:/usr/src/app/
    ports:
      - 8080:8080
    environment:
      - FASTAPI_PORT=8080
      - REDIS_PORT=6379
      - DB=postgresql
      - DB_USER=postgres
      - DB_PASSWORD=postgres_pass
      - DB_HOST=db
      - DB_PORT=5432
      #- REDIS_SERVER=redis://redis:6379
    depends_on:
      - redis
      - db

  worker:
    build:
      context: ./backend
      dockerfile: Dockerfile_worker
    command: python -m models_billing.inference_queue.worker
    #command: sh
    # volumes:
    #   - ./triton-facade:/usr/src/app
    #   - ./images_storage:/usr/src/app/images_storage
    environment:
      - FASTAPI_PORT=8080
      - REDIS_PORT=6379
      - DB=postgresql
      - DB_USER=postgres
      - DB_PASSWORD=postgres_pass
      - DB_HOST=db
      - DB_PORT=5432
      #- REDIS_SERVER=redis://redis:6379
    depends_on:
      - web
      - redis
      - db

  redis:
    image: redis:7-alpine

  db:
    image: postgres:12.17-alpine3.19
    # ports:
    #  - 5432:5432
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres_pass